from __future__ import annotations

from pathlib import Path
import re


REPO_ROOT = Path(__file__).resolve().parents[1]
SLIDES_DIR = REPO_ROOT / "slides"
OUTPUT_PATH = REPO_ROOT / "_generated" / "slides.qmd"
SUPPORTED_EXTENSIONS = {".md", ".qmd"}
HEADING_PATTERN = re.compile(r"^(#{1,6})\s+(.*)$")


def iter_entries(path: Path) -> list[Path]:
    return sorted(
        (
            entry
            for entry in path.iterdir()
            if not entry.name.startswith(".")
            and (entry.is_dir() or entry.suffix in SUPPORTED_EXTENSIONS)
        ),
        key=lambda entry: entry.name,
    )


def normalize_heading(content: str, level: int, source: Path) -> str:
    lines = content.splitlines()

    for index, line in enumerate(lines):
        stripped = line.lstrip()

        if not stripped:
            continue

        match = HEADING_PATTERN.match(stripped)
        if match is None:
            raise ValueError(
                f"{source.relative_to(REPO_ROOT)} must start with a Markdown heading."
            )

        lines[index] = f"{'#' * level} {match.group(2)}"
        return "\n".join(lines).rstrip() + "\n"

    raise ValueError(f"{source.relative_to(REPO_ROOT)} is empty.")


def read_slide(path: Path, level: int) -> str:
    return normalize_heading(path.read_text(encoding="utf-8"), level=level, source=path)


def build_slide_sections() -> list[str]:
    if not SLIDES_DIR.exists():
        raise FileNotFoundError(f"Missing slides directory: {SLIDES_DIR}")

    sections: list[str] = []

    for entry in iter_entries(SLIDES_DIR):
        if entry.is_dir():
            children = [child for child in iter_entries(entry) if child.is_file()]
            if not children:
                continue

            sections.append(read_slide(children[0], level=1))
            sections.extend(read_slide(child, level=2) for child in children[1:])
            continue

        sections.append(read_slide(entry, level=1))

    if not sections:
        raise ValueError("No slide content found in slides/.")

    return sections


def main() -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    sections = build_slide_sections()
    rendered = [
        "<!-- Generated by scripts/build_slides.py; edit slides/ instead. -->",
        *sections,
    ]
    OUTPUT_PATH.write_text("\n".join(rendered).rstrip() + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
